services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: Harry-portfolio
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
